// `vibefield-plugin docs` — the plugin-authoring reference, generated from the
// contracts (§5.4 item 7; P8-D8 promoted it from "nice" to load-bearing, because
// the ten-minute bar is measured with an agent whose ONLY input is these files).
//
// Everything structural is DERIVED: field tables walk the zod objects, limits
// come from PLUGIN_LIMITS, the vocabularies come from the enums, the invariants
// come from running the schema, the refusal catalog comes from the kit's own
// table, and every example is validated before it is written. What remains
// hand-written is the connective prose — and the ctx table's present-iff rules,
// which are anchored to the SDK's source by test.
//
// Byte-stability is a requirement, not an accident: `pnpm gen:docs` emits these
// files and `gen:check` diffs them, so a clock, a version stamp, or an
// unordered map anywhere in here would make the gate flap.

import {
  CanvasSystemContribution,
  CONTRACTS_VERSION,
  CommandContribution,
  HOST_SINGLETON_MODULE_SPECIFIERS,
  McpContribution,
  PLUGIN_CAPABILITY_ELIGIBILITY,
  PLUGIN_LIMITS,
  PluginCapabilityContribution,
  PluginManifestV1Shape,
  PropSpec,
  ServiceContribution,
  ServiceMethodContribution,
  SettingsContribution,
  SurfaceContribution,
  WIDGET_CATEGORIES,
  WidgetContribution,
} from "@vibefield/contracts";
import {
  type CtxFaceRow,
  invariantRows,
  RENDERER_CTX_FACES,
  SERVICE_CTX_FACES,
} from "./docs-anchors";
import { contributionSlice, jsonBlock, loadExamples } from "./docs-examples";
import { catalogRows } from "./refusals";
import { type FieldDoc, fieldsOf, variantsOf } from "./schema-walk";
import { R10_ALLOWED_DOOR, R10_FORBIDDEN_MODULES } from "./wall";

const BANNER = [
  "<!-- GENERATED by `vibefield-plugin docs` — do not edit by hand.",
  "     Regenerate with `pnpm gen:docs`; `pnpm verify` fails on stale output. -->",
].join("\n");

/**
 * One table cell, made safe for markdown without becoming unreadable as PLAIN
 * TEXT — which matters more than usual here, because the primary reader is an
 * agent looking at the raw file.
 *
 * Two hazards, both seen in real schema messages: a `|` inside a cell ends the
 * cell (the activation rule's `onStartup | onWidget:…` did exactly that), and an
 * angle-bracketed placeholder like `<name>` is swallowed as an HTML tag when the
 * page is rendered. So a cell carrying markdown-significant characters is
 * wrapped in a code span — unless it already carries one, in which case the
 * author formatted it deliberately and it is left alone.
 */
export function cell(text: string): string {
  const wrapped =
    !text.includes("`") && /[<>*_[\]]/.test(text) && text.length > 0 ? `\`${text}\`` : text;
  return wrapped.replaceAll(/(?<!\\)\|/g, "\\|");
}

function table(headers: string[], rows: string[][]): string {
  const line = (cells: string[]): string => `| ${cells.join(" | ")} |`;
  return [
    line(headers),
    line(headers.map(() => "---")),
    ...rows.map((row) => line(row.map(cell))),
  ].join("\n");
}

function fieldTable(fields: FieldDoc[]): string {
  return table(
    ["field", "type", "required", "rules"],
    fields.map((f) => [
      `\`${f.name}\``,
      f.type,
      f.required ? "yes" : "no",
      f.constraints.join("; ") || "—",
    ]),
  );
}

function section(title: string, body: string[]): string {
  return [`## ${title}`, "", ...body].join("\n");
}

const FENCE = "```";

function fence(language: string, content: string): string {
  return [`${FENCE}${language}`, content, FENCE].join("\n");
}

function ctxTable(rows: readonly CtxFaceRow[]): string {
  return table(
    ["face", "type", "present"],
    rows.map((r) => [`\`${r.face}\``, r.type, r.presence]),
  );
}

function document(title: string, blocks: string[]): string {
  return `${[BANNER, "", `# ${title}`, "", ...blocks].join("\n").trimEnd()}\n`;
}

// --- README --------------------------------------------------------------------

function readme(): string {
  const examples = loadExamples();
  return document("Authoring a VibeField plugin", [
    "A plugin is a directory with a manifest, one built entry module, and nothing else",
    "the host has to be told about. The manifest is the contract: it DECLARES what the",
    "plugin contributes, and code BINDS implementations to those declarations at",
    "activation. Anything a plugin can do, it declares first.",
    "",
    "These files are generated from the contracts themselves, so they describe the",
    `schema this app actually enforces (contracts ${CONTRACTS_VERSION}).`,
    "",
    section("The files", [
      table(
        ["file", "what it answers"],
        [
          ["`manifest.md`", "every manifest field, its rules, and the cross-field invariants"],
          ["`contributions.md`", "each contribution kind's shape, with a worked example"],
          ["`widgets.md`", "props, conflict groups, ports, and how a widget binds"],
          ["`context.md`", "`activate(ctx)`, which faces exist when, and the lifecycle"],
          ["`cli.md`", "the build → check → pack → dev-link loop"],
          ["`refusals.md`", "every refusal code the kit can emit, and what fixes it"],
        ],
      ),
      "",
    ]),
    section("The shortest real plugin", [
      "Three files you write, two the tools produce.",
      "",
      "```",
      "my-plugin/",
      "  src/manifest.ts           # TS authors the manifest",
      "  src/renderer.tsx          # the entry source: activate + the component",
      "  scripts/emit-manifest.ts  # writes the canonical JSON",
      "  vibefield.plugin.json     # EMITTED — never hand-edited",
      "  dist/renderer.js          # BUILT — the artifact the manifest names",
      "  package.json              # build + gen:manifest scripts",
      "```",
      "",
      "The manifest, complete and minimal:",
      "",
      fence("json", jsonBlock(examples.minimal.manifest)),
      "",
      `*(${examples.minimal.source})*`,
      "",
      "The renderer module it names:",
      "",
      fence(
        "tsx",
        // Signatures MIRROR plugins/note/src/widget.tsx (the shipped proof
        // widget) — docs-anchors.test.ts pins each call against that file, so
        // an example that drifts from shipping code fails generation review.
        // The P8d-3 rehearsal caught the previous bare-<CardShell> form: it
        // did not compile, and these docs are the bar agent's ONLY input.
        [
          'import { defineRendererPlugin } from "@vibefield/plugin-sdk";',
          'import type { WidgetComponentProps } from "@vibefield/plugin-sdk/canvas";',
          'import { CardShell } from "@vibefield/plugin-sdk/ui";',
          "",
          "function NoteCard({ world, entity }: WidgetComponentProps) {",
          "  return (",
          "    <CardShell world={world} entity={entity}>",
          "      <p>hello from a plugin</p>",
          "    </CardShell>",
          "  );",
          "}",
          "",
          "export default defineRendererPlugin({",
          "  activate(ctx) {",
          "    ctx.widgets.register({",
          '      type: "com.example.notes",',
          "      binding: { component: NoteCard },",
          "    });",
          "  },",
          "});",
        ].join("\n"),
      ),
      "",
      "The manifest is AUTHORED in TypeScript and EMITTED to that JSON — you never",
      "write the JSON by hand, and `check` refuses it if you do:",
      "",
      fence(
        "ts",
        [
          "// src/manifest.ts — typed against the contract, so a mistake is a type error",
          'import type { PluginManifestV1 } from "@vibefield/contracts";',
          "",
          "export const manifest: PluginManifestV1 = {",
          "  manifestVersion: 1,",
          '  id: "com.example.notes",',
          '  version: "0.1.0",',
          '  title: "Example Notes",',
          '  engines: { app: "^0.1.0", contracts: "^0.1.0" },',
          '  entries: { renderer: "./dist/renderer.js" },',
          '  activation: ["onWidget:com.example.notes"],',
          "  capabilities: [],",
          "  contributes: { widgets: [/* … */] },",
          "};",
        ].join("\n"),
      ),
      "",
      fence(
        "ts",
        [
          "// scripts/emit-manifest.ts — the one writer of the canonical artifact",
          'import { dirname, join } from "node:path";',
          'import { fileURLToPath } from "node:url";',
          'import { emitManifest } from "@vibefield/plugin-build";',
          'import { manifest } from "../src/manifest";',
          "",
          "emitManifest(",
          "  manifest,",
          '  join(dirname(fileURLToPath(import.meta.url)), "..", "vibefield.plugin.json"),',
          ");",
        ].join("\n"),
      ),
      "",
      "The package.json that wires it together — the build script is the whole build:",
      "",
      fence(
        "json",
        jsonBlock({
          name: "@example/plugin-notes",
          private: true,
          type: "module",
          scripts: {
            build: "plugin-build",
            "gen:manifest": "tsx scripts/emit-manifest.ts",
            test: "vitest run",
          },
          dependencies: {
            "@vibefield/contracts": "workspace:*",
            "@vibefield/plugin-sdk": "workspace:*",
          },
          peerDependencies: { react: "^19.0.0" },
        }),
      ),
      "",
      "And the loop:",
      "",
      fence(
        "sh",
        [
          "pnpm gen:manifest                 # manifest.ts → vibefield.plugin.json",
          "pnpm build                        # plugin-build: renderer (+ service) bundles",
          "vibefield-plugin check .          # the whole suite, as verdicts",
          "vibefield-plugin dev-link .       # put it where a dev session finds it",
        ].join("\n"),
      ),
      "",
      "Do not hand-author this layout: the scaffolder emits it working. Start every",
      "new plugin with",
      "",
      fence(
        "sh",
        [
          'create-plugin --id vendor.name --title "My Plugin" --dir plugins/name',
          "#   (in this repo: pnpm exec create-plugin …; targets under plugins/ or",
          "#    examples/plugins/ join the workspace — run pnpm install after)",
          "pnpm plugin check plugins/name    # a fresh scaffold is check-clean from birth",
          "pnpm playground plugins/name      # its starter states render as verdicts",
        ].join("\n"),
      ),
      "",
      "The scaffold ships `manifest.ts` + its emit script, one working CardShell",
      "widget, `playground/states.ts` starter states, the manifest conformance test,",
      "and the build preset — every file already in the shape `check` demands.",
      "",
    ]),
    section("The rules that catch people first", [
      "- **Every contributed id is owned by the plugin id.** A widget type is `<id>` or",
      "  `<id>.<name>`; commands, surfaces and systems are `<id>.<name>`; custom",
      "  capabilities are `x.<id>.<name>`.",
      "- **Declare before you bind.** `ctx.widgets.register` throws for a type the",
      "  manifest does not declare, and `check` refuses a declaration nothing binds.",
      "- **The manifest is emitted, not written.** `vibefield.plugin.json` is canonical",
      "  key-sorted JSON; its hash is the plugin's identity. Hand-edit it and `check`",
      "  refuses with `manifest-stale`.",
      "- **The SDK is the only door.** Plugin code imports `@vibefield/plugin-sdk`",
      "  (plus `/ui`, `/canvas`), `@vibefield/contracts` types, and `react`. Nothing",
      "  else — no host packages, no Electron, no Node builtins.",
      "- **Absent APIs are absent, never stubbed.** If a face is missing from `ctx`,",
      "  the manifest did not ask for it. See `context.md`.",
      "",
    ]),
  ]);
}

// --- manifest ------------------------------------------------------------------

function manifestDoc(): string {
  const examples = loadExamples();
  const limits = Object.entries(PLUGIN_LIMITS).map(([key, value]) => [`\`${key}\``, String(value)]);
  return document("The manifest", [
    "`vibefield.plugin.json` is the installed contract. It is EMITTED from a typed",
    "`manifest.ts` by `plugin-build`'s manifest stage, canonicalized (keys sorted,",
    "2-space indent, one trailing newline) so the same manifest always produces the",
    "same bytes — the plugin's `manifestHash` and its packed artifact's sha256 both",
    "derive from them.",
    "",
    section("Top-level fields", [
      fieldTable(fieldsOf(PluginManifestV1Shape)),
      "",
      "`engines.app` and `engines.contracts` are semver ranges the host checks before",
      "a plugin loads; `engines.platforms` narrows to `darwin`/`linux`/`win32`.",
      "`entries` names BUILT `.js` artifacts, `./`-relative, inside the plugin",
      "directory. `host` applies only to `entries.service` and defaults to `worker`.",
      "",
    ]),
    section("Cross-field invariants", [
      "These are checked together, after the field rules. The message column is what",
      "the schema itself says — `check` prints it verbatim with a pointer.",
      "",
      table(
        ["rule", "pointer", "message"],
        invariantRows().map((r) => [r.topic, `\`${r.pointer}\``, r.message]),
      ),
      "",
    ]),
    section("Activation events", [
      "`activation` lists the events that make the host load the plugin:",
      "",
      "- `onStartup` — service entries only, requires the `background` capability and a",
      "  `backgroundReason` that says why in the user's words.",
      "- `onWidget:<widget type>`, `onCommand:<command id>`, `onSurface:<surface id>`,",
      "  `onService:<x.pluginId.method>` — each must name something this manifest",
      "  declares.",
      "",
      "An empty `activation` list is legal: the plugin is registered, and loads when",
      "something it contributes is first reached.",
      "",
    ]),
    section("Capabilities", [
      "`capabilities` is a REQUEST, and it is a ceiling rather than a grant: the host",
      "intersects it with what the entry kind may hold, what the user has revoked, and",
      "what the source policy allows. A capability the renderer may not hold is denied",
      "with `entry-kind` even when the manifest asks for it.",
      "",
      table(
        ["capability", "renderer", "service"],
        Object.entries(PLUGIN_CAPABILITY_ELIGIBILITY)
          .sort(([a], [b]) => a.localeCompare(b))
          .map(([capability, eligibility]) => [
            `\`${capability}\``,
            eligibility?.renderer === true ? "yes" : "—",
            eligibility?.service === true ? "yes" : "—",
          ]),
      ),
      "",
      "Anything absent from this table is not plugin-eligible at all. A plugin may also",
      "declare its OWN capabilities (`x.<pluginId>.<name>`) to gate calls into its",
      "dynamic service methods — see `contributions.md`.",
      "",
    ]),
    section("Limits", [
      "Every string and collection in a manifest is bounded (§7.1). The numbers:",
      "",
      table(["limit", "value"], limits),
      "",
    ]),
    section("A manifest that uses most of it", [
      fence("json", jsonBlock(examples.service.manifest)),
      "",
      `*(${examples.service.source})*`,
      "",
    ]),
  ]);
}

// --- contributions --------------------------------------------------------------

function contributionsDoc(): string {
  const examples = loadExamples();
  const widgetSlice = contributionSlice(examples.minimal, "widgets");
  const commandSlice = contributionSlice(examples.commandsAndSurfaces, "commands");
  const surfaceSlice = contributionSlice(examples.commandsAndSurfaces, "surfaces");
  const settingsSlice = contributionSlice(examples.service, "settings");
  const servicesSlice = contributionSlice(examples.service, "services");
  const systemsSlice = contributionSlice(examples.service, "systems");
  const capabilitiesSlice = contributionSlice(examples.service, "capabilities");
  const mcpSlice = contributionSlice(examples.service, "mcp");

  const kindSection = (
    title: string,
    schema: unknown,
    slice: { source: string; value: unknown } | undefined,
    prose: string[],
  ): string =>
    section(title, [
      ...prose,
      "",
      fieldTable(fieldsOf(schema)),
      "",
      ...(slice === undefined
        ? []
        : [fence("json", jsonBlock(slice.value)), "", `*(${slice.source})*`, ""]),
    ]);

  return document("Contributions", [
    "`contributes` is where a plugin declares what it adds. Each kind below is a key",
    "under it; every one is optional, and the cross-field invariants in `manifest.md`",
    "decide which entry module and which capability each kind requires.",
    "",
    kindSection("Widgets", WidgetContribution, widgetSlice, [
      "A widget is a canvas card. The manifest owns its DURABLE schema — the type, its",
      "props, its size behaviour — and code binds a component to it. `widgets.md` is",
      "the deep end; the field table is here.",
      "",
      `Categories: ${WIDGET_CATEGORIES.map((c) => `\`${c}\``).join(", ")}.`,
    ]),
    kindSection("Commands", CommandContribution, commandSlice, [
      "A command is an invocable action the spine places (palette, context menus, HUD,",
      "godview). The spine owns ordering, args validation and provenance; the plugin",
      "binds a handler with `ctx.commands.register(id, handler)`.",
    ]),
    kindSection("Surfaces", SurfaceContribution, surfaceSlice, [
      "A surface is a React component the spine mounts in a named slot. The SLOT is",
      "manifest truth — a component cannot choose where it appears — and only a side",
      "panel is given a `requestClose()`. Bind with `ctx.surfaces.register(id, Component)`.",
    ]),
    kindSection("Settings", SettingsContribution, settingsSlice, [
      "Declared keys only. Each property carries a title, a scope (`user` syncs,",
      "`device` stays local, `secret` never leaves the keychain) and a JSON Schema the",
      "host validates writes against. Reading them from code requires `storage.self`,",
      "and the values arrive through `ctx.settings`.",
    ]),
    kindSection("Dynamic services", ServiceContribution, servicesSlice, [
      "A service entry may expose methods under its own `x.<pluginId>` namespace. Each",
      "method declares its kind, the capability a caller must hold, whether it is",
      "idempotent, and its JSON Schemas. The host validates both directions, so an",
      "invalid input never reaches the provider and an invalid output becomes",
      "`PLUGIN_SCHEMA_VIOLATION`.",
      "",
      "Method kinds:",
      "",
      ...(variantsOf(ServiceMethodContribution) ?? []).map(
        (v) => `- \`${v.discriminant}\` — ${v.fields.map((f) => `\`${f.name}\``).join(", ")}`,
      ),
    ]),
    kindSection("Canvas systems", CanvasSystemContribution, systemsSlice, [
      "A system runs after the engine step, inside a budget the spine enforces. The",
      "`reason` field is the honesty tax: frame cadence is a scarce power, and a system",
      "says why it needs one.",
    ]),
    kindSection("Custom capabilities", PluginCapabilityContribution, capabilitiesSlice, [
      "A plugin that provides services can define the capabilities that gate them:",
      "`x.<pluginId>.<name>`, with a risk level the user sees when granting.",
    ]),
    kindSection("MCP", McpContribution, mcpSlice, [
      "`tools` project already-declared service methods to agents; `servers` declare",
      "external MCP servers whose transport settings come from DECLARED settings keys",
      "(a url from a `device`-scope key, a secret from a `secret`-scope one) — never",
      "from literals in the manifest.",
    ]),
  ]);
}

// --- widgets ---------------------------------------------------------------------

function widgetsDoc(): string {
  const propVariants = variantsOf(PropSpec) ?? [];
  return document("Widgets", [
    "A widget type is declared once in the manifest and bound once in code. The",
    "declaration is DURABLE: the canvas stores documents against it, so its type name,",
    "prop names and group names outlive any particular implementation.",
    "",
    section("Declaring", [
      fieldTable(fieldsOf(WidgetContribution)),
      "",
      "`surface` picks the renderer: `dom` for an HTML card, `gl` for a 3D island with",
      "DOM chrome portaled under it. `sizeMode` and `defaultSize` set the prefab the",
      "host builds; `interaction` carries the canvas's own flags (selectable, movable,",
      "resizable, snap, dragOn, solid, sweepContained).",
      "",
    ]),
    section("Props", [
      "Props are the widget's durable data. Each is one of these kinds:",
      "",
      table(
        ["kind", "fields", "notes"],
        propVariants.map((v) => [
          `\`${v.discriminant}\``,
          v.fields.map((f) => `\`${f.name}\``).join(", ") || "—",
          v.discriminant === "json"
            ? "`inner` describes the nested shape; the value rides one string cell"
            : v.discriminant.endsWith("-ref")
              ? "an opaque host reference — the host resolves it, the plugin never parses it"
              : "—",
        ]),
      ),
      "",
      "Every kind also accepts `optional` and `mutable` (default true). A default must",
      "satisfy its own spec — an enum default outside `options`, a number outside",
      "`min`/`max`, a string over `maxLength` are all refused at emit.",
      "",
    ]),
    section("Conflict groups", [
      "Props that change together belong in a named group. The name is durable: the",
      "engine generates a component named `<widget type>:<group name>` from it, and two",
      "editors writing different groups of the same widget never conflict.",
      "",
      "- Omitting `groups` is the common case — ungrouped props join the engine's",
      "  default `props` group.",
      "- A group name matches `[a-z][a-z0-9-]*`, every member must be a declared prop,",
      "  and a prop belongs to at most one group.",
      "- An immutable prop (`mutable: false`) belongs to no group at all.",
      "",
      fence(
        "ts",
        [
          "props: {",
          '  title: { kind: "string", default: "" },',
          '  body: { kind: "string", default: "" },',
          '  color: { kind: "enum", options: ["amber", "slate"], default: "amber" },',
          "},",
          "groups: {",
          '  text: ["title", "body"],   // one editor typing',
          '  style: ["color"],          // another recolouring — no conflict',
          "},",
        ].join("\n"),
      ),
      "",
    ]),
    section("Ports", [
      "A node-style widget declares ports; the engine renders and routes the wires.",
      "Each port has an `id`, a `side` (`n`/`e`/`s`/`w`), an optional `index` along that",
      "side, and an optional `accepts` list. Omitting `accepts` means it connects to",
      "anything. Port ids are unique within a widget.",
      "",
    ]),
    section("Binding", [
      "One `register` per declared type, during `activate`:",
      "",
      fence(
        "ts",
        [
          "ctx.widgets.register({",
          '  type: "com.example.notes",',
          "  binding: {",
          "    component: NoteCard,      // the card itself",
          "    chrome: NoteChrome,       // GL only: DOM chrome under the canvas",
          "    animated: true,           // GL only: per-frame island repaint",
          "    preview: NotePreview,     // tray preview override",
          "  },",
          "});",
        ].join("\n"),
      ),
      "",
      "`register` throws on an undeclared type and on a second bind of the same type in",
      "one activation. It returns a `Disposable`; the host disposes the binding when",
      "the activation ends, so you do not have to.",
      "",
    ]),
    section("Reading and writing props", [
      "The canvas hooks arrive through the SDK's `/canvas` door, never from ICE",
      "directly:",
      "",
      fence(
        "tsx",
        // Real signatures (mirrors plugins/note/src/widget.tsx; pinned by
        // docs-anchors.test.ts): useWidgetProps takes (world, entity, type),
        // and writes go through ops.setWidgetProps(entity, props).
        [
          'import { useOps, useWidgetProps, type WidgetComponentProps } from "@vibefield/plugin-sdk/canvas";',
          "",
          'const TYPE = "com.example.notes";',
          "",
          "function NoteCard({ world, entity }: WidgetComponentProps) {",
          "  const props = useWidgetProps<{ body: string }>(world, entity, TYPE);",
          "  const ops = useOps();",
          "  return (",
          "    <textarea",
          "      value={props.body}",
          "      onChange={(e) => ops.setWidgetProps(entity, { body: e.target.value })}",
          "    />",
          "  );",
          "}",
        ].join("\n"),
      ),
      "",
    ]),
  ]);
}

// --- context ----------------------------------------------------------------------

function contextDoc(): string {
  return document("activate(ctx)", [
    "A plugin module has exactly one entry point. Module top-level code MUST NOT do",
    "product work — no registration, no I/O, no timers — because the host imports the",
    "module before it decides whether to activate it. Everything starts in `activate`.",
    "",
    fence(
      "tsx",
      [
        'import { defineRendererPlugin } from "@vibefield/plugin-sdk";',
        "",
        "export default defineRendererPlugin({",
        "  activate(ctx) {",
        "    ctx.widgets.register({",
        '      type: "com.example.notes",',
        "      binding: { component: NoteCard },",
        "    });",
        "",
        '    const timer = setInterval(() => ctx.logger.debug("tick"), 1000);',
        "    return { dispose() { clearInterval(timer); } };   // deactivation",
        "  },",
        "});",
      ].join("\n"),
    ),
    "",
    "`activate` may be async, and may return a `Disposable` (or nothing). In renderer entries,",
    "every host-created registration, whatever `activate` returns, and everything passed to",
    "`ctx.track(...)` is owned by the activation. Cleanup is awaited in reverse acquisition order",
    "on reload, disable, or a failed activation half-way through. Use",
    "`ctx.track(label, resource)` when a diagnostic name is useful; tracking the same exact handle",
    "twice is safe and deduplicated.",
    "",
    section("Deadlines", [
      table(
        ["phase", "deadline"],
        [
          ["renderer `activate`", `${PLUGIN_LIMITS.RENDERER_ACTIVATE_DEADLINE_MS} ms`],
          ["service `activate`", `${PLUGIN_LIMITS.SERVICE_ACTIVATE_DEADLINE_MS} ms`],
          ["deactivate", `${PLUGIN_LIMITS.DEACTIVATE_DEADLINE_MS} ms`],
        ],
      ),
      "",
      "Miss one and the activation fails; the host disposes whatever was already",
      "registered rather than leaving it half-bound.",
      "",
    ]),
    section("The renderer context", [
      "Faces are present when the manifest earns them. An absent face is not a stub and",
      "not an error object — it is simply not there, so `ctx.settings?.get(…)` is how",
      "you ask for something optional.",
      "",
      ctxTable(RENDERER_CTX_FACES),
      "",
      "Use `ctx.effect(label, acquire)` for optional or replaceable setup. `acquire` receives a",
      "child-bound context; registrations made through that context roll back together if setup",
      "fails, while registrations deliberately made through the outer `ctx` keep root lifetime.",
      "",
      fence(
        "ts",
        [
          'await ctx.effect("optional-index", async (fx) => {',
          '  fx.commands?.register("com.example.notes.reindex", reindex);',
          '  fx.track("index-listener", listenForIndexChanges());',
          "});",
        ].join("\n"),
      ),
      "",
    ]),
    section("The service context", [
      "A service entry gets a different context: no widgets, no canvas, and the",
      "provider API instead.",
      "",
      ctxTable(SERVICE_CTX_FACES),
      "",
      "`ctx.plugin`, `ctx.signal`, `ctx.logger`, `ctx.client`, `ctx.settings`, and",
      "`ctx.storage` share the renderer shapes. Service entries currently expose the compatible",
      "`ctx.track(resource)` form; the labeled overload and child-bound `ctx.effect` are renderer",
      "entry surfaces.",
      "",
    ]),
    section("Commands and surfaces", [
      fence(
        "ts",
        [
          'ctx.commands?.register("com.example.tools.tidy", (args, invocation) => {',
          "  // invocation: { source, windowId, selection, userGesture } — spine truth,",
          "  // never claimable by the handler",
          "});",
          "",
          'ctx.surfaces?.register("com.example.tools.panel", ToolsPanel);',
          "// ToolsPanel receives { slot, windowId } — and requestClose() on a side panel",
        ].join("\n"),
      ),
      "",
      "Both refuse an id the manifest does not declare, and both refuse a double-bind.",
      "",
    ]),
    section("Talking to the product", [
      "`ctx.client` is this plugin's own connection: calls arrive at the daemon",
      "attributed to the plugin, with the plugin's granted scopes — never the window's.",
      "",
      fence(
        "ts",
        [
          'const docs = await ctx.client.request("docs.list", {});',
          "const sub = await ctx.client.subscribe(",
          '  "plugins.subscribe",',
          "  {},",
          '  (event) => ctx.logger.info("registry moved", { event }),',
          ");",
          "ctx.track({ dispose: sub.unsubscribe }); // safe even when a host adapter auto-owns it",
        ].join("\n"),
      ),
      "",
      "A method the plugin lacks the capability for is refused by the daemon, not by a",
      "check in the SDK: the SDK surfaces are a veneer, and the caller matrix is the",
      "enforcement.",
      "",
    ]),
    section("The import wall", [
      "What plugin runtime code may import, and nothing else:",
      "",
      ...R10_ALLOWED_DOOR.map((mod) => `- \`${mod}\``),
      "",
      "These are refused — `check` reports `wall-violation` with the file and line:",
      "",
      ...R10_FORBIDDEN_MODULES.map((mod) => `- \`${mod}\``),
      "",
      "Node builtins (`node:*`) are refused too — a renderer plugin has no filesystem,",
      "and a service plugin asks the host through `ctx`. `scripts/` and `test/` are",
      "authoring-time subtrees and are exempt.",
      "",
      "Separately, these are the specifiers the host's import map RESOLVES at load",
      "time, so a bundle may leave them as bare imports instead of bundling a second",
      "copy:",
      "",
      ...HOST_SINGLETON_MODULE_SPECIFIERS.map((mod) => `- \`${mod}\``),
      "",
      "The two lists overlap on purpose and do not contradict each other: the canvas",
      "engine is resolvable at runtime because the SDK's own re-exports need it, while",
      "a plugin that imports `@vibecook/ice` directly is still refused. Reach the canvas",
      "through `@vibefield/plugin-sdk/canvas`. You never configure bundler externals by",
      "hand either way — `plugin-build` owns that list.",
      "",
    ]),
  ]);
}

// --- cli --------------------------------------------------------------------------

function cliDoc(): string {
  return document("The authoring loop", [
    "Every command is non-interactive, prints one line per row, and exits `0` (all",
    "rows passed), `1` (at least one refusal) or `2` (the kit itself failed). With",
    "`--json` each line is one verdict object:",
    "",
    fence(
      "json",
      jsonBlock({
        level: "refuse",
        check: "manifest",
        code: "manifest-invalid",
        pointer: "/contributes/widgets/0/type",
        expected: "declare com.example.notes.card, or register the declared type",
        detail: "widget type other.card must be com.example.notes or com.example.notes.<name>",
      }),
    ),
    "",
    "`level` is `pass`, `note` (an honest absence — a row that could not run and says",
    "why) or `refuse`. Only `refuse` affects the exit code.",
    "",
    section("Commands", [
      table(
        ["command", "what it does"],
        [
          ["`check <dir>`", "the whole suite: manifest, wall, schemas, binding, artifacts"],
          ["`inspect <dir>`", "resolved contributions, grants, hashes, entries, state count"],
          ["`pack <dir>`", "the deterministic `.vfplugin` + its sha256"],
          ["`dev-link <dir>`", "put the plugin where a developer-mode session finds it"],
          ["`submit <dir>`", "the registry index row for an artifact, and the human step"],
          [
            "`release lookup <id> --index <path> --key <public key file>`",
            "read a signed index, refuse a bad signature",
          ],
          ["`index sign <index> --key <secret key file>`", "sign an index (maintainers)"],
          ["`docs --out <dir>`", "regenerate these files"],
        ],
      ),
      "",
    ]),
    section("check", [
      "The rows, in order:",
      "",
      table(
        ["row", "what it proves"],
        [
          ["`manifest`", "validates as `PluginManifestV1`, and the committed bytes are canonical"],
          ["`wall`", "plugin sources import only through the SDK door (R10)"],
          ["`schema`", "every declared JSON Schema compiles, as the daemon compiles it"],
          [
            "`activation`",
            "declarations and bindings match exactly, and deactivation leaks nothing",
          ],
          ["`artifact`", "declared entries exist and import only mappable specifiers"],
        ],
      ),
      "",
      "`check` never requires a build. With no `dist/` the artifact and activation rows",
      "emit notes instead of refusals, and the command can still pass.",
      "",
    ]),
    section("pack", [
      "`pack` walks the installed bundle — `vibefield.plugin.json`, `dist/**`,",
      "`assets/**`, and any declared entry module — and nothing else. `test/`,",
      "`scripts/` and `playground/` are authoring-time and never travel in an artifact.",
      "",
      "The zip is deterministic: STORE-only, a fixed timestamp, bytewise-sorted names.",
      "The same tree packs to the same bytes on any machine, which is what lets a",
      "registry pin its sha256 and a reviewer diff it.",
      "",
    ]),
    section("dev-link", [
      "`dev-link` copies the installed bundle into the dev-linked plugin root, where a",
      "developer-mode session discovers it. It is a COPY, not a symlink, and that is",
      "forced by two host rules: discovery keeps only real directories, and the module",
      "authority refuses an artifact whose realpath escapes its plugin root.",
      "",
      "So the loop is: build, link, reload.",
      "",
      fence(
        "sh",
        [
          "pnpm build                        # produce dist/",
          "vibefield-plugin dev-link .        # copy into the dev root, print where",
          "# then, in the app: enable developer mode and call plugins.reload",
          "",
          "vibefield-plugin dev-link . --remove   # undo",
        ].join("\n"),
      ),
      "",
      "The root is `--root` if given, else the first entry of `FIELDD_PLUGIN_DEV_ROOTS`,",
      "else the repository's development root. The command always prints which it used.",
      "",
    ]),
    section("Publishing", [
      "`submit` computes the artifact's sha256 and prints the exact index row a",
      "registry entry is made of. It builds nothing and uploads nothing — the artifact",
      "url is a placeholder you replace with the release asset's, and adding the row to",
      "the index repository is a pull request a human opens.",
      "",
      "`release lookup` verifies the index's detached signature BEFORE reading a row",
      "out of it, and `index sign` produces that signature. Neither touches the",
      "network: pass a local path or a `file://` url.",
      "",
    ]),
  ]);
}

// --- refusals -----------------------------------------------------------------------

function refusalsDoc(): string {
  const rows = catalogRows();
  const refusals = rows.filter((r) => r.level === "refuse");
  const notes = rows.filter((r) => r.level === "note");
  return document("Refusal codes", [
    "Every code `check` and its siblings can emit. `code` is stable — branch on it.",
    "`expected` in the verdict is the concrete fix for that instance; the guidance",
    "column is the general one.",
    "",
    section("Refusals (exit 1)", [
      table(
        ["code", "row", "meaning", "fix"],
        refusals.map((r) => [`\`${r.code}\``, r.check, r.meaning, r.guidance]),
      ),
      "",
    ]),
    section("Notes (exit 0)", [
      "A note is a row that could not run, or a fact worth saying. It never fails a",
      "command — honest absence beats a blank.",
      "",
      table(
        ["code", "row", "meaning", "what it suggests"],
        notes.map((r) => [`\`${r.code}\``, r.check, r.meaning, r.guidance]),
      ),
      "",
    ]),
  ]);
}

// --- the emission -----------------------------------------------------------------

export const DOC_FILES = [
  "README.md",
  "manifest.md",
  "contributions.md",
  "widgets.md",
  "context.md",
  "cli.md",
  "refusals.md",
] as const;

/** filename → content, deterministic in both. */
export function generateDocs(): Map<string, string> {
  return new Map<string, string>([
    ["README.md", readme()],
    ["manifest.md", manifestDoc()],
    ["contributions.md", contributionsDoc()],
    ["widgets.md", widgetsDoc()],
    ["context.md", contextDoc()],
    ["cli.md", cliDoc()],
    ["refusals.md", refusalsDoc()],
  ]);
}
