import SwarmPhysics
import Testing

@testable import FieldAgents

@Suite struct AgentClassificationTests {
  @Test func missingStateReadsAsWorking() {
    #expect(classifyAgentStatus(nil) == .working)
  }

  @Test func terminalLifecyclesLeaveTheField() {
    #expect(classifyAgentStatus(AgentRuntimeState(lifecycle: .exited)) == nil)
    #expect(classifyAgentStatus(AgentRuntimeState(lifecycle: .failed)) == nil)
  }

  @Test func permissionsOutrankEverything() {
    let state = AgentRuntimeState(
      activeTurn: true,
      permissions: [AgentPermission(tool: "Bash")],
      toolRuns: [AgentToolRun(title: "Bash")])
    #expect(classifyAgentStatus(state) == .waiting)
  }

  @Test func anySignOfWorkIsWorking() {
    #expect(classifyAgentStatus(AgentRuntimeState(lifecycle: .starting)) == .working)
    #expect(classifyAgentStatus(AgentRuntimeState(activeTurn: true)) == .working)
    #expect(classifyAgentStatus(AgentRuntimeState(activeReasoning: true)) == .working)
    #expect(
      classifyAgentStatus(AgentRuntimeState(toolRuns: [AgentToolRun(title: "Edit")])) == .working)
    #expect(classifyAgentStatus(AgentRuntimeState(taskCount: 2)) == .working)
  }

  @Test func quietReadySessionIsIdle() {
    #expect(classifyAgentStatus(AgentRuntimeState()) == .idle)
  }

  /// The desktop's deliberate off-by-one: idle wears the calm working tier,
  /// working ignites, only waiting gets the loud tier.
  @Test func bubbleVisualMapping() {
    #expect(bubbleVisual(for: .idle) == AgentBubbleVisual(
      status: .idle, appearance: .working, isIgnited: false))
    #expect(bubbleVisual(for: .working) == AgentBubbleVisual(
      status: .working, appearance: .working, isIgnited: true))
    #expect(bubbleVisual(for: .waiting) == AgentBubbleVisual(
      status: .waiting, appearance: .waiting, isIgnited: false))
  }

  @Test func radiusFollowsAppearanceTier() {
    let parameters = SwarmParameters.default
    #expect(bubbleRadius(for: .idle, parameters: parameters) == 40)
    #expect(bubbleRadius(for: .working, parameters: parameters) == 50)
    #expect(bubbleRadius(for: .waiting, parameters: parameters) == 70)
  }
}

@Suite struct AgentDetailTests {
  @Test func detailTellsTheTruth() {
    #expect(agentDetail(nil, status: .working) == "starting")
    #expect(
      agentDetail(
        AgentRuntimeState(permissions: [AgentPermission(tool: "Bash")]), status: .waiting)
        == "permission · Bash")
    #expect(
      agentDetail(AgentRuntimeState(permissions: [AgentPermission()]), status: .waiting)
        == "permission required")
    #expect(
      agentDetail(AgentRuntimeState(toolRuns: [AgentToolRun(title: "pnpm verify")]),
        status: .working) == "pnpm verify")
    #expect(
      agentDetail(AgentRuntimeState(toolRuns: [AgentToolRun()]), status: .working)
        == "using tool")
    #expect(agentDetail(AgentRuntimeState(activeReasoning: true), status: .working) == "thinking")
    #expect(agentDetail(AgentRuntimeState(activeTurn: true), status: .working) == "responding")
    #expect(agentDetail(AgentRuntimeState(), status: .idle) == "idle")
  }
}

@Suite struct AgentIdentityHueTests {
  /// Cross-language goldens: generated by running the desktop's `agentColor`
  /// FNV-1a hash (godview `agent-status.ts`) under Node on 2026-07-29.
  /// If this test fails, the Swift port has drifted from the JS original —
  /// fix the port, never the goldens.
  @Test func matchesDesktopHashGoldens() {
    #expect(agentIdentityHue("vibe-field") == 136)
    #expect(agentIdentityHue("truffle") == 97)
    #expect(agentIdentityHue("chopsticks") == 136)
    #expect(agentIdentityHue("ghosttea") == 130)
    #expect(agentIdentityHue("session-0001") == 89)
    #expect(agentIdentityHue("9f31c2ab-77d1-4e02-b1a5-1cd1e0c1a001") == 105)
    #expect(agentIdentityHue("a") == 276)
    #expect(agentIdentityHue("") == 61)
  }
}
